apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "rpts-shared-infrastructure"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_j_to_z/rpts-shared-infrastructure
    github.com/project-slug: hmcts/rpts-shared-infrastructure
  tags:
    - terraform
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=fact-tech
      title: "#fact-tech on Slack"
      icon: chat
spec:
  type: service
  lifecycle: production
  owner: dts_rpts
